Set generate_token to true for Cognito app clients
This is required for any client that supports client credentials flow.  Without this set the following error is received from AWS API :
   InvalidOAuthFlowException: client_credentials flow can not be selected if client does not have a client secret.

 I omitted it initially as including it will force replacement of the existing App clients in integration, but this should be OK as they will be replaced by new ones with new client_secrets.